version: '3.8'

services:
  antimg:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=your-super-secret-key-change-in-production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - GIN_MODE=release
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
    driver: local