name: API-CORE Branch Docker Build

on:
  push:
    branches: [ "api-core" ]
  pull_request:
    branches: [ "api-core" ]

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io
  OWNER: neurocoda
  IMAGE_NAME: antimg-api  

jobs:
  docker-api-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean buildx cache
        run: docker buildx prune -af

      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Generate multi-registry metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest           
            type=sha,prefix=,suffix=        
            type=ref,event=branch           
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      
      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
            REVISION=${{ github.sha }}
            BUILDTIME=${{ github.event.head_commit.timestamp || github.job.started_at }}
            CACHE_BUSTER=${{ github.sha }}
          cache-from: type=gha,scope=${{ github.workflow }}-api-core
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-api-core

      
      - name: Verify pushed tags
        if: always()
        run: |
          echo "=== Generated Tags ==="
          echo "${{ steps.meta.outputs.tags }}"
          echo "=== Labels ==="
          echo "${{ steps.meta.outputs.labels }}"
